version: '3.8'

services:

  app-fruit:
    container_name: fruit-api-container
    build: .
    ports:
      - "8080:8080"
    environment:

      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_NAME=fruit_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql-db
    networks:
      - fruit-network


  mysql-db:
    container_name: mysql-db-container
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:

      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fruit_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fruit-network


volumes:
  mysql_data:

networks:
  fruit-network: